JAVAC = javac
JAVAFLAGS = -g

S0_SRC = S0/S0.java S0/S0Helper.java
S1_SRC = S1/S1.java S1/S1Helper.java
S2_SRC = S2/S2.java S2/S2Helper.java
S3_SRC = S3/S3.java S3/S3Helper.java
S4_SRC = S4/S4.java S4/S4Helper.java
S5_SRC = S5/S5.java S5/S5Helper.java
S6_SRC = S6/S6.java S6/S6Helper.java
S7_SRC = S7/S7.java S7/S7Helper.java
C1_SRC = C1/C1.java C1/C1Helper.java
C2_SRC = C2/C2.java C2/C2Helper.java
C3_SRC = C3/C3.java C3/C3Helper.java
C4_SRC = C4/C4.java C4/C4Helper.java
C5_SRC = C5/C5.java C5/C5Helper.java

all: s0 s1 s2 s3 s4 s5 s6 s7 c1 c2 c3 c4 c5

s0:
	$(JAVAC) $(JAVAFLAGS) $(S0_SRC)

s1:
	$(JAVAC) $(JAVAFLAGS) $(S1_SRC)
s2:
	$(JAVAC) $(JAVAFLAGS) $(S2_SRC)
s3:
	$(JAVAC) $(JAVAFLAGS) $(S3_SRC)
s4:
	$(JAVAC) $(JAVAFLAGS) $(S4_SRC)
s5:
	$(JAVAC) $(JAVAFLAGS) $(S5_SRC)
s6:
	$(JAVAC) $(JAVAFLAGS) $(S6_SRC)
s7:
	$(JAVAC) $(JAVAFLAGS) $(S7_SRC)
c1:
	$(JAVAC) $(JAVAFLAGS) $(C1_SRC)
c2:
	$(JAVAC) $(JAVAFLAGS) $(C2_SRC)
c3:
	$(JAVAC) $(JAVAFLAGS) $(C3_SRC)
c4:
	$(JAVAC) $(JAVAFLAGS) $(C4_SRC)
c5:
	$(JAVAC) $(JAVAFLAGS) $(C5_SRC)

clean:
	rm -f S0/*.class S1/*.class S2/*.class S3/*.class S4/*.class S5/*.class S6/*.class S7/*.class C1/*.class C2/*.class C3/*.class C4/*.class C5/*.class